### PR TITLE
Add CHECK_LICENSE permission as some apps may require it.

### PR DESCRIPTION
**Pull request by alinefr**
Some apps like 'I Love Hue' game asks for com.android.vending.CHECK_LICENSE. As it only needs the permission, it does not check anything, I think it may be worth to add this to FakeStore.

### CODE REVIEW

**Comment by ale5000-git** [comment]
+1

**Comment by tristan-k** [comment]
This essentially holds me off using my recently purchased `com.brit.swiftdark.substratum` because it complains about `This copy of Swift Dark is not licensed`.

**Comment by ale5000-git** [comment]
@mar-v-in: Any news about this?

**Comment by ale5000-git** [comment]
@mar-v-in: Any update about this?

**Comment by rugk** [comment]
@mar-v-in Could not you just merge this? It looks simple enough…

**Pull request merged**
