### PR TITLE
Create LicensingService stub

### PR DESCRIPTION
**Pull request by Uldiniad**

### CODE REVIEW

**Comment by Uldiniad** [comment]
Should fix (at least some of) the following issues
https://github.com/microg/GmsCore/issues/2050
https://github.com/microg/FakeStore/issues/47
https://gitlab.com/CalyxOS/calyxos/-/issues/1510
https://github.com/microg/GmsCore/issues/46

**Comment by chirayudesai** [comment]
Test: https://play.google.com/store/apps/details?id=com.sap.mdc.loblaw.nativ

Many of the other apps listed worked fine either way.

**Comment by vincentvidal** [comment]
A similar solution has been implemented in the FakeStore version distributed for iodéOS: through our f-droid repo [since March 14](https://gitlab.com/iode/os/apps/FakeStore/-/commit/7afc67799d7790e10e01828e1dcd79d71478cde2) and in iodéOS v4.1 released on April 2 (we left the aidl files taken [from here](https://github.com/google/play-licensing/tree/master/lvl_library/src/main/aidl/com/android/vending/licensing) for some experiments, although not useful for the stub).
I can confirm that many apps work with this patch, with the exception of Tasker as [reported by several users](https://community.iode.tech/t/downgrading-microg/1304/17), which was working without the stub.

**Comment by mar-v-in** [comment]
A similar, yet more complete version of the License Service was added as part of 464a546b59ee541c6b34e5baa5628eeb4b5766dd (I had the code lying around for several weeks but had not properly tested it yet).

**Pull request closed without merging**
